// Vložit nového uživatele
db.users.insertOne({
  User_ID: 118,
  Name: "John Doe",
  Email_Address: "johndoe@example.com",
  Username: "johndoe",
  Date_of_Birth: "1990-01-01",
  Gender: "Male",
  Location: "New York",
  Membership_Start_Date: "2024-05-01",
  Membership_End_Date: "2025-05-01",
  Subscription_Plan: "Annual",
  Payment_Information: "Visa",
  Renewal_Status: "Manual",
  Usage_Frequency: "Regular",
  Purchase_History: "Books",
  Favorite_Genres: "Fiction",
  Devices_Used: "Smart TV",
  Engagement_Metrics: "Medium",
  "Feedback/Ratings": 4.7,
  Customer_Support_Interactions: 2,
});

// Vložit více uživatelů najednou
db.users.insertMany([
  {
    User_ID: 119,
    Name: "Jane Smith",
    Email_Address: "janesmith@example.com",
    Username: "janesmith",
    Date_of_Birth: "1985-05-15",
    Gender: "Female",
    Location: "Los Angeles",
    Membership_Start_Date: "2024-05-01",
    Membership_End_Date: "2025-05-01",
    Subscription_Plan: "Monthly",
    Payment_Information: "Mastercard",
    Renewal_Status: "Auto-renew",
    Usage_Frequency: "Frequent",
    Purchase_History: "Electronics",
    Favorite_Genres: "Drama",
    Devices_Used: "Smartphone",
    Engagement_Metrics: "High",
    "Feedback/Ratings": 4.8,
    Customer_Support_Interactions: 1,
  },
  {
    User_ID: 120,
    Name: "Alice Johnson",
    Email_Address: "alicejohnson@example.com",
    Username: "alicejohnson",
    Date_of_Birth: "1975-03-10",
    Gender: "Female",
    Location: "Chicago",
    Membership_Start_Date: "2024-05-01",
    Membership_End_Date: "2025-05-01",
    Subscription_Plan: "Annual",
    Payment_Information: "Amex",
    Renewal_Status: "Manual",
    Usage_Frequency: "Occasional",
    Purchase_History: "Books",
    Favorite_Genres: "Horror",
    Devices_Used: "Tablet",
    Engagement_Metrics: "Low",
    "Feedback/Ratings": 4.2,
    Customer_Support_Interactions: 3,
  },
]);
